planning_plugin: chomp_interface/CHOMPPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
start_state_max_bounds_error: 0.1
planning_time_limit: 15.0
max_iterations: 800
max_iterations_after_collision_free: 100
smoothness_cost_weight: 0.1
obstacle_cost_weight: 0.1
learning_rate: 0.05
animate_path: false
add_randomness: false
smoothness_cost_velocity: 0.0
smoothness_cost_acceleration: 0.5
smoothness_cost_jerk: 0.5
hmc_discretization: 0.01
hmc_stochasticity: 0.005
hmc_annealing_factor: 0.99
use_hamiltonian_monte_carlo: false
ridge_factor: 0.001
use_pseudo_inverse: true
pseudo_inverse_ridge_factor: 1e-4
animate_endeffector: false
animate_endeffector_segment: "link_right"
joint_update_limit: 0.1
collision_clearance: 0.01
collision_threshold: 0.03
random_jump_amount: 1.0
use_stochastic_descent: true
enable_failure_recovery: true
max_recovery_attempts: 20
trajectory_initialization_method: "cubic-spline"
# trajectory_initialization_method: "quintic-spline"